export const countries = {
    "Punjab": [
      "Lahore",
      "Rawalpindi",
      "Faisalabad",
      "Multan",
      "Gujranwala",
      "Bahawalpur",
      "Sialkot",
      "Sargodha",
      "Sheikhupura",
      "Jhang",
      "Gujrat",
      "Sahiwal",
      "Wah",
      "Mianwali",
      "Attock",
      "Rahim Yar Khan",
      "Okara",
      "Layyah",
      "Vehari",
      "Burewala",
      "Khanewal",
      "Muzaffargarh",
      "Jhelum",
      "Chiniot",
      "Kasur",
      "Nankana Sahib"
    ],
    "Sindh": [
      "Karachi",
      "Hyderabad",
      "Sukkur",
      "Larkana",
      "Nawabshah",
      "Mirpur Khas",
      "Jacobabad",
      "Shikarpur",
      "Dadu",
      "Tando Adam",
      "Khairpur",
      "Sanghar",
      "Ghotki",
      "Badin",
      "Thatta",
      "Umerkot",
      "Hala"
    ],
    "Khyber Pakhtunkhwa": [
      "Peshawar",
      "Mardan",
      "Abbottabad",
      "Swat",
      "Nowshera",
      "Kohat",
      "Mansehra",
      "Haripur",
      "Charsadda",
      "Dera Ismail Khan",
      "Chitral",
      "Bannu",
      "Swabi",
      "Batagram",
      "Hangu",
      "Tank",
      "Karak"
    ],
    "Balochistan": [
      "Quetta",
      "Gwadar",
      "Turbat",
      "Khuzdar",
      "Chaman",
      "Loralai",
      "Zhob",
      "Hub",
      "Mastung",
      "Sibi",
      "Kharan",
      "Nushki",
      "Kalat",
      "Killa Saifullah",
      "Panjgur",
      "Lasbela",
      "Dera Bugti",
      "Jaffarabad",
      "Nasirabad"
    ],
    "Islamabad Capital Territory": [
      "Islamabad"
    ],
    "Gilgit-Baltistan": [
      "Gilgit",
      "Skardu",
      "Chilas",
      "Ghanche",
      "Astore",
      "Kharmang",
      "Shigar",
      "Shangla",
      "Ghizer",
      "Hunza"
    ],
    "Azad Kashmir": [
      "Muzaffarabad",
      "Mirpur",
      "Kotli",
      "Bhimber",
      "Rawalakot",
      "Hattian",
      "Bagh",
      "Haveli"
    ]
}
